DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Restaurants;

CREATE TABLE Users (
    usr VARCHAR(32) NOT NULL,
    pass VARCHAR(32) NOT NULL ,
    email VARCHAR(60) NOT NULL ,
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    UNIQUE(email),
    UNIQUE(usr)
);

CREATE TABLE Restaurants (
    name VARCHAR(32) NOT NULL,
    city VARCHAR(32) NOT NULL,
    district VARCHAR(32) NOT NULL,
    country VARCHAR(32) NOT NULL,
    avgClass INTEGER,
    owner INTEGER REFERENCES Users(id),
    id INTEGER PRIMARY KEY AUTOINCREMENT
);
